name: Proton nopackage Arch Linux CI



jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo lib32-jack2
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp
          export CARGO_HOME="$PWD"
          cd wine-tkg-git 
          sed -i 's/_wayland_driver="false"/_wayland_driver="true"/' customization.cfg
          cd ..
          cd proton-tkg
          sed -i 's/distro=""/distro="archlinux"/' proton-tkg.cfg
          sed -i 's/uninstaller="false"/uninstaller="true"/' proton-tkg.cfg
          sed -i 's/autoinstall="false"/autoinstall="true"/' proton-tkg.cfg
          sed -i 's/LOCAL_PRESET=""/LOCAL_PRESET="none"/' proton-tkg.cfg
          sed -i 's/build_gstreamer="false"/build_gstreamer="true"/' proton-tkg.cfg
          sed -i 's/lib32_gstreamer="false"/lib32_gstreamer="true"/' proton-tkg.cfg
          touch tarplz
          yes|./proton-tkg.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: proton-tkg-build
          path: proton-tkg/built/*.tar
